# Generated by Django 2.2.5 on 2019-09-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=15)),
                ('user_last_name', models.CharField(max_length=15)),
                ('user_email', models.CharField(max_length=50)),
                ('user_phone', models.IntegerField(max_length=12, null=True)),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
    ]
