# Generated by Django 2.2.5 on 2019-09-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizMania_V2', '0003_auto_20190920_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_password',
            field=models.CharField(max_length=51),
        ),
    ]
