# Generated by Django 2.2.5 on 2019-09-21 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizMania_V2', '0004_auto_20190920_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userInfo',
        ),
    ]
